/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanList: typeof import('vant/es')['List']
  const VanLoading: typeof import('vant/es')['Loading']
  const VanPullRefresh: typeof import('vant/es')['PullRefresh']
  const VanSearch: typeof import('vant/es')['Search']
  const VanSticky: typeof import('vant/es')['Sticky']
  const VanTab: typeof import('vant/es')['Tab']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTabs: typeof import('vant/es')['Tabs']
}