/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const constructor: typeof import('@/projects/pc/components/layouts/function Object() { [native code] }/index.vue').default
}
